db:
  image: postgres:12-alpine
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_PASSWORD: password
    POSTGRES_USER: user
    POSTGRES_DB: contact_book
  ports:
    - '5432:5432'
  volumes:
    - ./volumes/contacts_book_db/pgdata:/var/lib/postgresql/data/pgdata
  restart: on-failure:10

